media: files
content:
  - name: Documents
    label: Documents
    type: collection
    path: docs
    fields:
      - { name: slug, label: Slug, type: string }
      - { name: sidebar_label, label: Sidebar Label, type: string }
      - { name: body, label: Body, type: rich-text }