media: files
content: 
 - name: documents
   lable: Documents
   type: collection
   path: docs
   view:
     fields: [ title, date ]
   fields:
     - { name: id, label: Id, type: string }
     - { name: title, label: Title, type: string }
     - { name: sidebar_label, label: Sidebar Label, type: string }
     - { name: body, label: Body, type: rich-text }