media: files
content: 
 - name: Documents
   lable: documents
   type: collection
   path: docs
   fields:
     - { name: category, label: カテゴリー, type: select, options: [] }
     - { name: slug, label: Slug, type: string }
     - { name: sidebar_label, label: Sidebar Label, type: string }
     - { name: body, label: Body, type: rich-text }