# Pages CMS設定ファイル - 最新のフォーマットに準拠
repository:
  owner: eito1011-JP
  name: Handbook
  branch: main

# コンテンツ設定
collections:
  - name: docs
    label: ドキュメント
    folder: docs
    create: true
    fields:
      - name: id
        label: ID
        widget: string
        required: true
      - name: title
        label: タイトル
        widget: string
        required: true
      - name: sidebar_label
        label: サイドバーラベル
        widget: string
        required: false
      - name: sidebar_position
        label: サイドバー位置
        widget: number
        required: false
      - name: description
        label: 説明
        widget: text
        required: false
      - name: tags
        label: タグ
        widget: list
        required: false
      - name: body
        label: 本文
        widget: markdown
        required: true

# メディア設定
media_folder: static/img
public_folder: /img

# 編集ワークフロー設定
publish_mode: editorial_workflow

# UI設定
locale: ja