media: files
content:
  - name: Documents
    label: Documents
    type: collection
    path: docs
    branch: cms-edits
    fields:
      - { name: slug, label: スラグ, type: string }
      - { name: sidebar_label, label: タイトル, type: string }
      - { name: body, label: 内容, type: rich-text }