backend:
  name: git-gateway
  branch: main  # メインブランチ
  repo: eito1011-JP/Handbook  # あなたのGitHubユーザー名/リポジトリ名
  open_authoring: true  # PRワークフローを有効化

# サイトURL
site_url: https://handbookapp.netlify.app
display_url: https://handbookapp.netlify.app

# 編集ワークフローを有効化
publish_mode: editorial_workflow

media_folder: static/img
public_folder: /img

# コンテンツコレクション（ドキュメント）の定義
collections:
  - name: docs
    label: Documentation
    folder: docs
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "ID", name: "id", widget: "string"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Sidebar Label", name: "sidebar_label", widget: "string", required: false}
      - {label: "Body", name: "body", widget: "markdown"}