backend:
  name: github
  repo: eito1011-JP/Handbook  # あなたのGitHubユーザー名/リポジトリ名
  branch: main  # メインブランチ
  base_url: https://api.netlify.com
  auth_endpoint: auth
  open_authoring: true  # これによりPRが作成されます

publish_mode: editorial_workflow  # 編集ワークフローを有効化

media_folder: static/img
public_folder: /img

# コンテンツコレクション（ドキュメント）の定義
collections:
  - name: docs
    label: Documentation
    folder: docs
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "ID", name: "id", widget: "string"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Sidebar Label", name: "sidebar_label", widget: "string", required: false}
      - {label: "Body", name: "body", widget: "markdown"}