name: Create PR from cms-edits to main

on:
  push:
    branches: [ cms-edits ]

jobs:
  create-cms-to-main-pr:
    if: github.event_name == 'push' && github.ref == 'refs/heads/cms-edits'
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Check Differences Between Branches
        id: check_diff
        run: |
          # コミットメッセージを取得
          COMMIT_MESSAGE=$(git log -1 --pretty=%B)
          echo "message=${COMMIT_MESSAGE}" >> "$GITHUB_OUTPUT"
          
          # mainブランチとcms-editsブランチの差分を確認
          git fetch origin main:main
          DIFF_COUNT=$(git rev-list --count main..cms-edits)
          echo "diff_count=${DIFF_COUNT}" >> "$GITHUB_OUTPUT"
      
      - name: Create Pull Request
        if: ${{ steps.check_diff.outputs.diff_count != '0' }}
        run: |
          # 新しいPRを作成
          gh pr create \
            -B main \
            -H cms-edits \
            -t "【CMS更新】${{ steps.check_diff.outputs.message }}" \
            -a ${{ github.actor }} \
            -b "このPRはcms-editsブランチからの更新を含みます。" || echo "PRの作成をスキップしました（既に存在する可能性があります）"