name: Create PR from cms-edits to main and Update gh-pages

on:
  push:
    branches: [ cms-edits ]
  pull_request:
    types: [ closed ]
    branches: [ main ]

jobs:
  create-cms-to-main-pr:
    if: github.event_name == 'push' && github.ref == 'refs/heads/cms-edits'
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Check Differences Between Branches
        id: check_diff
        run: |
          # コミットメッセージを取得
          COMMIT_MESSAGE=$(git log -1 --pretty=%B)
          echo "message=${COMMIT_MESSAGE}" >> "$GITHUB_OUTPUT"
          
          # mainブランチとcms-editsブランチの差分を確認
          git fetch origin main:main
          DIFF_COUNT=$(git rev-list --count main..cms-edits)
          echo "diff_count=${DIFF_COUNT}" >> "$GITHUB_OUTPUT"
      
      - name: Create Pull Request
        if: ${{ steps.check_diff.outputs.diff_count != '0' }}
        run: |
          # 新しいPRを作成
          gh pr create \
            -B main \
            -H cms-edits \
            -t "【CMS更新】${{ steps.check_diff.outputs.message }}" \
            -a ${{ github.actor }} \
            -b "このPRはcms-editsブランチからの更新を含みます。" || echo "PRの作成をスキップしました（既に存在する可能性があります）"

  update-gh-pages:
    if: github.event_name == 'pull_request' && github.event.pull_request.merged == true && github.event.pull_request.base.ref == 'main'
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: main
      
      - name: Setup Git User
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
      
      - name: Update gh-pages Branch
        run: |
          # gh-pagesブランチをフェッチ
          git fetch origin gh-pages:gh-pages || git checkout -b gh-pages
          
          # mainの変更をgh-pagesにマージ
          git checkout gh-pages
          git merge main -m "Merge main into gh-pages after CMS update" || {
            echo "Merge conflict occurred. Using main content."
            git checkout --theirs .
            git add .
            git commit -m "Resolve conflicts in favor of main content"
          }
          
          # gh-pagesブランチをプッシュ
          git push origin gh-pages