name: Create Pull Request from CMS Edits

on:
  push:
    branches:
      - cms-edits

jobs:
  create-pr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: cms-edits
          fetch-depth: 0  # 全履歴を取得
      
      - name: Check if changes exist between cms-edits and main
        id: check_changes
        run: |
          git fetch origin main
          if [ -z "$(git diff --name-only origin/main)" ]; then
            echo "No changes found between cms-edits and main"
            echo "has_changes=false" >> $GITHUB_OUTPUT
          else
            echo "Changes found between cms-edits and main"
            echo "has_changes=true" >> $GITHUB_OUTPUT
          fi
      
      - name: Create Pull Request
        if: steps.check_changes.outputs.has_changes == 'true'
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: cms-edits
          base: main
          title: "Docs Update from Pages CMS [${{ github.event.head_commit.message }}]"
          body: |
            Pages CMSで編集されたドキュメントの更新です。
            差分を確認の上、マージしてください。
          commit-message: "Update docs from Pages CMS"
          labels: "documentation, cms-update"