name: Create PR to main

on:
  push:
    branches: 
      - 'feature/**'

jobs:
  create-feature-to-main-pr:
    if: startsWith(github.ref, 'refs/heads/feature/')
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Check Differences Between Branches
        id: check_diff
        run: |
          # コミットメッセージを取得
          COMMIT_MESSAGE=$(git log -1 --pretty=%B)
          echo "message=${COMMIT_MESSAGE}" >> "$GITHUB_OUTPUT"
          
          # ブランチ名を取得
          BRANCH_NAME=${GITHUB_REF#refs/heads/}
          echo "branch_name=${BRANCH_NAME}" >> "$GITHUB_OUTPUT"
          
          # mainブランチとfeatureブランチの差分を確認
          git fetch origin main:main
          DIFF_COUNT=$(git rev-list --count main..${BRANCH_NAME})
          echo "diff_count=${DIFF_COUNT}" >> "$GITHUB_OUTPUT"
      
      - name: Create Pull Request
        if: ${{ steps.check_diff.outputs.diff_count != '0' && contains(steps.check_diff.outputs.message, '更新内容の提出') }}
        run: |
          # PRのタイトルからユーザー名を抽出
          BRANCH_NAME="${{ steps.check_diff.outputs.branch_name }}"
          USERNAME=$(echo $BRANCH_NAME | sed -E 's/feature\/([^_]+)_.*/\1/')
          
          # 新しいPRを作成
          gh pr create \
            -B main \
            -H "$BRANCH_NAME" \
            -t "【${USERNAME}の更新】${{ steps.check_diff.outputs.message }}" \
            -b "このPRはfeatureブランチからの更新を含みます。\n\n**ブランチ**: ${{ steps.check_diff.outputs.branch_name }}" || echo "PRの作成をスキップしました（既に存在する可能性があります）"