name: Laravel tests on PR

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
    paths:
      - 'laravel-api/**'
      - 'database/test.db.sql'
      - '.github/workflows/laravel-test.yml'

jobs:
  php-tests:
    if: ${{ github.event.pull_request.draft == false && !startsWith(github.head_ref, 'branch_') }}
    runs-on: ubuntu-latest

    env:
      APP_ENV: testing
      DB_CONNECTION: sqlite
      # DB_DATABASE はここでは未設定（下の Set DB path で注入）

    defaults:
      run:
        working-directory: laravel-api

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: pdo_sqlite, sqlite3, mbstring, dom, fileinfo
          coverage: none
          tools: composer:v2

      - name: Validate composer files
        run: composer validate --no-check-publish

      - name: Install dependencies
        run: composer install --no-interaction --no-progress --prefer-dist

      - name: Generate APP_KEY
        run: echo APP_KEY=$(php -r 'echo "base64:".base64_encode(random_bytes(32));') >> $GITHUB_ENV

      # ← ここで後続ステップ用の DB_DATABASE を“注入”
      - name: Set DB path (per-job)
        run: echo "DB_DATABASE=$RUNNER_TEMP/test.db" >> $GITHUB_ENV

      - name: Ensure sqlite3 CLI is available
        run: sudo apt-get update && sudo apt-get install -y sqlite3

      - name: Prepare SQLite (fresh file + WAL + timeout)
        run: |
          rm -f "$DB_DATABASE"
          sqlite3 "$DB_DATABASE" 'PRAGMA journal_mode=WAL; PRAGMA busy_timeout=60000;'

      - name: Initialize database schema from SQL dump
        run: sqlite3 "$DB_DATABASE" < database/test.db.sql

      - name: Clear config cache
        run: php artisan config:clear

      - name: Seed master data
        run: php artisan db:seed --force -n

      - name: Run tests
        run: php artisan test --colors=never
